### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::share()

### ISSUE THREAD

**Issue by Saradimi** [harishanchu/Laravel-FTP#49] opened 2017-01-27 23:54 UTC
Hi,

Your package give me the following error on Laravel 5.4 : 

```
FatalThrowableError in FtpServiceProvider.php line 33:
Call to undefined method Illuminate\Foundation\Application::share()
```

Is this caused by a recent update of Laravel ?
Thank you very much.

**Comment by harishanchu** [comment] 2017-01-28 09:26
Yes, it is caused by a recent update of Laravel.
 
However it's been fixed in the master branch. Now I have tagged the latest changes to v2.0.2. Therefor updating your package will fix the issue.

Thanks.

**Closed by harishanchu** 2017-01-28 09:26 UTC

**Comment by Saradimi** [comment] 2017-01-28 10:52
Perfect ! Thank you ;)
